# The minimum amount of time before PVP is toggled on/off in minutes
minPVP: 3
# The maximum amount of time before PVP is toggled on/off in minutes
maxPVP: 10

# Colour codes can be used for all messages using the & symbol (see http://ess.khhq.net/mc/)
messages:
   enabled:
      # The title to be shown when PVP is turned on
      title: "&cPVP is now &lENABLED&r&c!"
      # The subtitle (under the title) to be shown when PVP is turned on
      subtitle: "&7Good luck!"
      # The message to be posted in chat when PVP is turned on (leave blank for no message)
      message: "&c&l[ForF]&r&f PVP is now enabled."
   disabled:
      # The title to be shown when PVP is turned off
      title: "&aPVP is now &lDISABLED&r&a!"
      # The subtitle (under the title) to be shown when PVP is turned off
      subtitle: "&7You can rest... for now!"
      # The message to be posted in chat when PVP is turned off (leave blank for no message)
      message: "&2&l[ForF]&r&f PVP is now disabled."
      
# All sounds must be in the valid Spigot sounds (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
sound:
   # The sound to be played when PVP is turned on
   enabled: "ENTITY_ENDER_DRAGON_AMBIENT"
   # The sound to be played when PVP is turned off
   disabled: "BLOCK_BEACON_ACTIVATE"

# Colour codes can be used for the title using the & symbol (see http://ess.khhq.net/mc/)
bar:
  # The style of the bar (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html)
  style: "SOLID"

  enabled:
    # The title for when PVP is on
    title: "&6PVP is &4&lENABLED" 
    # The bar colour when PVP is on (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html)
    colour: "RED"
  disabled:
    # The title for when PVP is off
    title: "&6PVP is &2&lDISABLED" 
    # The bar colour when PVP is off (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html)
    colour: "GREEN"