# The minimum amount of time before PVP is toggled on/off in minutes
minPVP: 3
# The maximum amount of time before PVP is toggled on/off in minutes
maxPVP: 10

# Colour codes can be used for all messages using the & symbol (see http://ess.khhq.net/mc/)
messages:
   enabled:
      # The title to be shown when PVP is turned on
      title: "&cPVP is now &lENABLED&r&c!"
      # The subtitle (under the title) to be shown when PVP is turned on
      subtitle: "&7Good luck!"
      # The message to be posted in chat when PVP is turned on (leave blank for no message)
      message: "&c&l[ForF]&r&f PVP is now enabled."
   disabled:
      # The title to be shown when PVP is turned off
      title: "&aPVP is now &lDISABLED&r&a!"
      # The subtitle (under the title) to be shown when PVP is turned off
      subtitle: "&7You can rest... for now!"
      # The message to be posted in chat when PVP is turned off (leave blank for no message)
      message: "&2&l[ForF]&r&f PVP is now disabled."
      
# All sounds must be in the valid Spigot sounds (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
sound:
   # The sound to be played when PVP is turned on
   enabled: "ENTITY_ENDER_DRAGON_AMBIENT"
   # The sound to be played when PVP is turned off
   disabled: "BLOCK_BEACON_ACTIVATE"